version: '3.7'

services:
  api-db:
      image: postgres
      container_name: api-db
      volumes:
        - './configs/db/dbApi/:/var/lib/postgresql/data'
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "54333:5433"

  api-server:
    build:
      context: .
      dockerfile: Dockerfile-develop
    container_name: api-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './:/code'
    ports:
      - "8282:8000"
    environment:
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=api-db
      - PGPORT=54333
      - MYSECRET=ejiujídjaonduagduoadyouiaydbiyu23y768705*¨%987GBJHGouY¨()*&%897gcybsa098d7c568
      - MYDEBUG=True
    depends_on:
      - api-db
