version: '3.7'

services:
  postgres:
    image: postgres
    container_name: Postgres-api
    volumes:
      - './configs/db/postgres/:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=sippe
      - POSTGRES_USER=sippe
      - POSTGRES_PASSWORD=sippe2023
    ports:
      - "54333:5433"
    restart: always

  django:
    build:
      context: .
      dockerfile: Dockerfile.Develop
    container_name: Django-api
    command: python setup.py && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/api/
    ports:
      - "8282:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=
      - PGDATABASE=sippe
      - PGUSER=sippe
      - PGPASSWORD=sippe2023
      - PGHOST=postgres
      - PGPORT=5433
      - MYSECRET=insecure-v@f)l361(joj_3-ie-^=)r$rvv3d1l_v&2%o*_gf^dp*_%zb^8*¨%987GBJHGouY¨()*&%897gcybsa098d7c568
      - MYDEBUG=False
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    image: redis
    container_name: Redis-api
    volumes:
      - "./configs/db/redis/:/data"
    ports:
      - "6379:6379"
    restart: always
