#DOCKER COMPOSE
#docker-compose up -d
version: '3.8'

services:

# Postgres
  secedu-pg-api:
    image: postgres
    container_name: secedu-pg-api
    restart: always
    environment:
      - POSTGRES_DB=secedu
      - POSTGRES_USER=secedu
      - POSTGRES_PASSWORD=ep4X1!br
    volumes:
      - 'B:\workspace\volumes\postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - secedu_network

# Django
  secedu-dj-api:
    build:
      context: ./secedu-django-api/
      dockerfile: Dockerfile
    container_name: secedu-dj-api
    command: gunicorn core.wsgi:application --bind 0.0.0.0:7000 --workers 2
    depends_on:
      - secedu-pg-api
    volumes:
      - ./secedu-django-api/:/api/
      - B:\workspace\volumes\dataset:/usr/src/api/dataset/
      - B:\SIPPE\FTP:/usr/src/api/ftp/
    ports:
      - "7000:7000"
    environment:
      - PGDATABASE=secedu
      - PGUSER=secedu
      - PGPASSWORD=ep4X1!br
      - PGHOST=secedu-pg-api
      - PGPORT=5432
      - MYSECRET=78cdsvc7sdavb07nvar87ynbdravs7by87yvb7ab09se7vybrsd7vyd9
      - MYDEBUG=False
      - ALLOWED_HOSTS=sippeserver01.ddns.net,localhost,
      - FPT_PATH=/usr/src/api/ftp/
      - DATASET_PATH=/usr/src/api/dataset/
      - BROKER_URL=amqp://secedu:ep4X1!br@localhost:5672
      - REDIS_URL=redis://localhost:6379/0
    restart: always
    networks:
      - secedu_network


networks:
  secedu_network:
    driver: bridge
