#DOCKER COMPOSE
#docker-compose up -d
version: '3.7'

services:

  # Postgres
  secedu-pg-api:
    image: postgres
    container_name: secedu-pg-api
    restart: always
    environment:
      - POSTGRES_DB=secedu
      - POSTGRES_USER=secedu
      - POSTGRES_PASSWORD=ep4X1!br
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    networks:
      - secedu_dj_network

  # Django
  secedu-dj-api:
    build:
      context: ./secedu-dj-api/
      dockerfile: Dockerfile
    container_name: secedu-dj-api
    command: "./entrypoint.sh"
    depends_on:
      - secedu-pg-api
      - secedu-rmq-task
    restart: always
    environment:
      - PGDATABASE=secedu
      - PGUSER=secedu
      - PGPASSWORD=ep4X1!br
      - PGHOST=secedu-pg-api
      - PGPORT=5432
      - MYSECRET=insecure-v@f)l361(joj_3-ie-^=)r$rvv3d1l_v&2%o*_gf^dp*_%zb^8*¨%987GBJHGouY¨()*&%897gcybsa098d7c568
      - MYDEBUG=False
    volumes:
      - ./secedu-dj-api:/api
      - ./volumes/dataset:/api/medias/fotos/
    ports:
      - "9000:9000"
    networks:
      - secedu_dj_network
      - secedu_rmq_network
      - secedu_rds_network

  # Flask
  secedu-fk-task:
    #image: secedu-fk-task:latest
    build: 
      context: ./secedu-fk-task/app/
      dockerfile: Dockerfile
    container_name: secedu-fk-task
    depends_on:
      - secedu-rds-tack
      - secedu-rmq-task
    restart: always
    volumes:
      - ./secedu-fk-task/app/api/:/app
      - ./volumes/dataset/:/app/dataset
    ports:
      - "5000:5000"
    networks:
      - secedu_rmq_network
      - secedu_rds_network
  
  # RabbitMQ
  secedu-rmq-task:
    image: rabbitmq:3-management
    container_name: secedu-rmq-task
    restart: always
    volumes:
      - ./volumes/rabbitMQ:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=secedu
      - RABBITMQ_DEFAULT_PASS=ep4X1!br
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - secedu_rmq_network
  
  # Redis-Stack RediSearch 
  secedu-rds-tack:
    image:  redis/redis-stack
    container_name: secedu-rds-tack
    restart: always
    volumes:
        - ./volumes/redis:/data
    ports:
        - "6379:6379" 
        - "8001:8001" 
    networks:
        - secedu_rds_network

networks:
  secedu_kc_network:
    driver: bridge
  secedu_dj_network:
    driver: bridge
  secedu_rds_network:
    driver: bridge
  secedu_rmq_network:
    driver: bridge



