#DOCKER COMPOSE
#docker-compose up -d
version: '3.7'

services:

# Postgres
  secedu-pg-api:
    image: postgres
    container_name: secedu-pg-api
    restart: always
    environment:
      - POSTGRES_DB=secedu
      - POSTGRES_USER=secedu
      - POSTGRES_PASSWORD=ep4X1!br
    volumes:
      - 'B:\workspace\volumes\postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
      - secedu_dj_network

# Django
  secedu-dj-api:
    build:
      context: ./secedu-dj-api/
      dockerfile: Dockerfile
    container_name: secedu-dj-api
    command: "bash entrypoint.sh"
    depends_on:
      - secedu-pg-api
    restart: always
    environment:
      - PGDATABASE=secedu
      - PGUSER=secedu
      - PGPASSWORD=ep4X1!br
      - PGHOST=secedu-pg-api
      - PGPORT=5432
      - MYSECRET=insecure-v@f)l361(joj_3-ie-^=)r$rvv3d1l_v&2%o*_gf^dp*_%zb^8*¨%987GBJHGouY¨()*&%897gcybsa098d7c568
      - MYDEBUG=False
    volumes:
      - ./secedu-dj-api:/api
      - B:\workspace\volumes\medias:/api/medias/fotos/
      - B:\SIPPE\FTP:/api/ftp/
    ports:
      - "7000:9000"
    networks:
      - secedu_dj_network


networks:
  secedu_dj_network:
    driver: bridge


    
# Flask