version: '3.10'
services:    
    rest-python:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rest-python
        ports:
            - "8087:8087" 
        environment:
            - REDIS_SERVER=redis-stack
            - REDIS_PORT=6379
            - REDIS_INDEX=idx:movie
        networks:
            - redisearch
        restart: always
        depends_on:
            - redis-stack  

networks:
    redisearch:
        driver: bridge
