version: '3.10'
services:

    # Start RediSearch 
    redis-stack:
        image:  redis/redis-stack:latest
        container_name: redis-stack
        ports:
            - "6379:6379" 
            - "8001:8001" 
        networks:
            - redisearch-gettingstarted
        volumes:
            - ./redisearch-docker/dataset:/dataset
            - ./redis:/data`
            
    # Iniciar o redis-stack para executar o script de carregamento e sair 
    redis-stack-2:
        image:  redis/redis-stack:latest
        container_name: redis-stack-2
        ports:
            - "6380:6379" 
        networks:
            - redisearch-gettingstarted
        volumes:
            - ./redisearch-docker/dataset:/dataset
        command:
            [ "sh", "./dataset/import-data.sh" ]
        depends_on:
            - redis-stack      

    rest-python:
        build:
            context: ./redisearch-python-rest
            dockerfile: Dockerfile
        container_name: rest-python
        ports:
            - "8087:8087" 
        environment:
            - REDIS_SERVER=redis-stack
            - REDIS_PORT=6379
            - REDIS_INDEX=idx:movie
        networks:
            - redisearch-gettingstarted
        restart: always
        depends_on:
            - redis-stack  

networks:
    redisearch-gettingstarted:
        driver: bridge
